select * from worker;
select * from product;
select * from orders;
select * from orders1;
select * from order_detail;
select * from ORDER_DETAIL_VIEW2;
select * from cart_view;
select * from noticelist;
SELECT * FROM tab;
SELECT * FROM members;
SELECT * FROM member;
SELECT * FROM qna;
SELECT * FROM EVENT;
delete from banner;
select count(*) from order_view where id like '%one%';