DROP SEQUENCE oseq;
CREATE SEQUENCE oseq START WITH 1 INCREMENT BY 1;

DROP SEQUENCE cseq;
CREATE SEQUENCE cseq START WITH 1 INCREMENT BY 1;

DROP SEQUENCE nseq;
CREATE SEQUENCE nseq START WITH 1 INCREMENT BY 1;

DROP SEQUENCE odseq;
CREATE SEQUENCE odseq START WITH 1 INCREMENT BY 1;

DROP SEQUENCE rseq;
CREATE SEQUENCE rseq START WITH 1 INCREMENT BY 1;

DROP SEQUENCE pseq;
CREATE SEQUENCE pseq START WITH 1 INCREMENT BY 1;

DROP SEQUENCE qseq;
CREATE SEQUENCE qseq START WITH 1 INCREMENT BY 1;

DROP SEQUENCE eseq;
CREATE SEQUENCE eseq START WITH 1 INCREMENT BY 1;

DROP SEQUENCE mseq;
CREATE SEQUENCE mseq START WITH 1 INCREMENT BY 1;

DROP SEQUENCE rvseq;
CREATE SEQUENCE rvseq START WITH 1 INCREMENT BY 1;

